### ISSUE TITLE
Support partial writes to socket channel

### ISSUE THREAD

**Issue by jfallows** [reaktivity/nukleus-tcp.java#3]
Even though Java exposes the send buffer size option [SO_SNDBUF](https://docs.oracle.com/javase/8/docs/api/java/net/SocketOptions.html#SO_SNDBUF) for socket channels, the available window size for the socket channel is known to the kernel but not exposed to the application.

Therefore it may be necessary to heuristically determine the effective window size for the socket channel based on successful writes versus incomplete writes. This would also take into consideration any bottleneck at the kernel due to massive number of concurrent connections and any bottlenecks at the network device due to bandwidth limitations.

If a socket channel has advertised (say) 8192 bytes available window size, and attempts to write 2048 bytes, but partially completes only 1536 bytes, then the remaining 512 bytes must be cached and re-attempted when the socket channel becomes writable again via [OP_WRITE](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/SelectionKey.html#OP_WRITE).

Note: it is advisable to briefly attempt a spin write to complete the write before requiring use of the cache to handle the partial write.

In addition, if any more of the already offered 8192 - 2048 = 6144 bytes arrive, they must also be cached to help maintain the guarantee that all data is written in consistent order to the socket channel.

While this is not a significant issue for an individual socket channel, we must successfully bound the total memory used for partial writes even when many socket channels exhibit the same behavior.

Note: it does not seem reasonable to send a negative window update to help reduce write pressure unless tolerance can be maintained for exceeding the new window size to allow for `DATA` frames already in-flight. This would also imply a less strict definition of window size for flow control in general across all nuklei.

**Comment by cmebarrow** [comment]
Tasks
- [ ] Find a way to force partial writes at the TCP level for testing purposes
- [ ] Add integration tests for partial writes when tcp nukleus is acting as server
- [ ] Add integration tests for partial writes when tcp nukleus is acting as client
- [ ] Complete the design for the memory "slab"
- [ ] Implement the memory "slab" with a comprehensive unit test
- [ ] Implement spin writes
- [ ] Implement handling of partial write (store data until socket is writable)

**Comment by cmebarrow** [comment]
For counter, see Counters class. Could expose through TCPController or some new class (like TCPCounters).  Counters are located at start of the control file.
