### ISSUE TITLE
How to configure max guaranteed streams, max window size per route?

### ISSUE THREAD

**Issue by cmebarrow** [reaktivity/nukleus-tcp.java#4]
We need to think of capacity as a guarantee of the maximum number of connections (streams) that are supported without any  streams being reset due to network congestion at the TCP level (partial writes). It may make sense to allow this to be configured per route, as part of a TCP extension for the route control protocol frame, or even for all nuklei (as part of the core control protocol). That would satisfy use cases where the expected number of users varies per service. 

To bound the memory used to store temporary pending writes we also need to assume a maximum window per stream (the maximum window size advertised by the TCP nukleus to a source nukleus). Again, it may make sense for this to be configured per route rather than globally.

**Comment by cmebarrow** [comment]
@jfallows Please set the "question" label - I don't seem to be able to do it.

**Comment by jfallows** [comment]
These values should be scoped by route and defined in `TcpRouteEx`, see #6.
